### ISSUE TITLE
API errors with internal call trace

### ISSUE THREAD

**Issue by DaneelTrevize** [ccpgames/esi-issues#381]
```
Refreshing fleet cache from CREST failed with the response:Traceback (most recent call last):
  File "e:\jenkins\workspace\server_TRANQUILITY\branches\release\TRANQUILITY\carbon\common\lib\cherrypy\wsgiserver\__init__.py", line 1245, in communicate
  File "e:\jenkins\workspace\server_TRANQUILITY\branches\release\TRANQUILITY\carbon\common\lib\cherrypy\wsgiserver\__init__.py", line 775, in respond
  File "e:\jenkins\workspace\server_TRANQUILITY\branches\release\TRANQUILITY\carbon\common\lib\cherrypy\wsgiserver\__init__.py", line 2039, in respond
  File "e:\jenkins\workspace\server_TRANQUILITY\branches\release\TRANQUILITY\eve\server\script\eveserver\crestapi\crestapiService.py", line 213, in TimeoutRequestHandler
  File "e:\jenkins\workspace\server_TRANQUILITY\branches\release\TRANQUILITY\packages\ccpmetrics\crest.py", line 4, in process_request
  File "e:\jenkins\workspace\server_TRANQUILITY\branches\release\TRANQUILITY\packages\ccpmetrics\crest.py", line 11, in _get_tags
  File "e:\jenkins\workspace\server_TRANQUILITY\branches\release\TRANQUILITY\packages\ccpmetrics\crest.py", line 29, in _get_agent_tags
  File "e:\jenkins\workspace\server_TRANQUILITY\branches\release\TRANQUILITY\packages\ccpmetrics\crest.py", line 41, in _get_agent_data
ValueError: need more than 1 value to unpack
```
No, it's not via ESI but CREST. Yes, I don't care because it seems more important that it gets fixed for all.

**Comment by a-tal** [comment]
that sounds a lot like this

<img width="581" alt="screen shot 2017-05-09 at 10 06 59 am" src="https://cloud.githubusercontent.com/assets/1832772/25863098/4cf2c0fc-349f-11e7-9ba3-73c137b9e15b.png">

**Comment by DaneelTrevize** [comment]
Is that from CCP's dev slack??

**Comment by a-tal** [comment]
tweetfleet slack, #esi channel -- [get an invite here](https://www.fuzzwork.co.uk/tweetfleet-slack-invites/)
